In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("../input/mushrooms.csv")
data.head(6)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   
5     e         x           y         y       t    a               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   
5            c         b          n  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   
5                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  
5           o         p                 k          n       g  

[6 rows x 23 columns]

In [3]:
data.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [4]:
data['class'].unique()

array(['p', 'e'], dtype=object)

In [5]:
data.shape

(8124, 23)

In [6]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
for col in data.columns:
    data[col] = labelencoder.fit_transform(data[col])
 
data.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [7]:
print(data.groupby('class').size())


class
0    4208
1    3916
dtype: int64


In [8]:
X = data.iloc[:,1:23]  # all rows, all the features and no labels
y = data.iloc[:, 0]  # all rows, label only
X.head()
y.head()

0    1
1    0
2    0
3    1
4    0
Name: class, dtype: int32

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X=scaler.fit_transform(X)
X

array([[ 1.02971224,  0.14012794, -0.19824983, ..., -0.67019486,
        -0.5143892 ,  2.03002809],
       [ 1.02971224,  0.14012794,  1.76587407, ..., -0.2504706 ,
        -1.31310821, -0.29572966],
       [-2.08704716,  0.14012794,  1.37304929, ..., -0.2504706 ,
        -1.31310821,  0.86714922],
       ...,
       [-0.8403434 ,  0.14012794, -0.19824983, ..., -1.50964337,
        -2.11182722,  0.28570978],
       [-0.21699152,  0.95327039, -0.19824983, ...,  1.42842641,
         0.28432981,  0.28570978],
       [ 1.02971224,  0.14012794, -0.19824983, ...,  0.16925365,
        -2.11182722,  0.28570978]])

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=4)

In [30]:
from sklearn.svm import SVC
svm_model= SVC(gamma="auto")

In [31]:
tuned_parameters = {
 'C': [1, 10, 100,500, 1000], 'kernel': ['linear'],
 'degree': [2,3,4,5,6] , 'C':[1,10,100,500,1000] , 'kernel':['poly']
    }

In [32]:

from sklearn.model_selection  import GridSearchCV, RandomizedSearchCV

model_svm = RandomizedSearchCV(svm_model, tuned_parameters,cv=10,scoring='accuracy',n_iter=20)

In [33]:
model_svm.fit(X_train, y_train)
print(model_svm.best_score_)

1.0


In [34]:
print(model_svm.best_params_)

{'kernel': 'poly', 'degree': 3, 'C': 1000}


In [38]:
svm_model= SVC(kernel="poly",C=1000,degree=3,gamma="auto")

In [40]:
svm_model.fit(X_train, y_train)

SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [41]:
svm_model.score(X_test, y_test)

1.0

In [43]:
svm_model.dual_coef_ 

array([[-5.04423742e-02, -9.14749488e-01, -1.09592092e-01,
        -2.08560440e+00, -1.09658073e+00, -4.15208912e+00,
        -1.13192962e+01, -5.08181392e-02, -4.49648119e-02,
        -6.19249274e-02, -7.40653600e-01, -8.53605113e+00,
        -2.73421028e+00, -1.92936358e+00, -1.20555909e-01,
        -4.39146464e-01, -7.17942576e+00, -6.34560289e-02,
        -7.85773124e-02, -2.01699203e-02, -3.95565889e+00,
        -2.99131940e+00, -1.02400619e+01, -4.46165903e+00,
        -7.84814925e+00, -4.32148516e-01, -2.03544377e+00,
        -9.13693582e-02, -4.85170901e-01, -2.23461507e+00,
        -5.76114162e+00, -3.46983464e-01, -3.58581716e-01,
        -1.72313613e-02, -1.18943948e-01, -2.96719519e+00,
        -5.00673527e-01, -4.85487459e-01, -5.12795854e-02,
        -1.36182721e-02, -2.47927346e+00, -1.64324245e-01,
        -3.60025912e-01, -6.73576515e-01, -3.16978087e-01,
        -1.38631853e-03, -1.79307389e+00, -8.50147114e-02,
        -8.60777995e-02, -1.60972283e-01, -1.00467504e+0

In [44]:
from sklearn_porter import Porter

In [47]:
porter = Porter(svm_model, language='java')
output = porter.export(embed_data=True)
print(output)

class SVC {

    private enum Kernel { LINEAR, POLY, RBF, SIGMOID }

    private int nClasses;
    private int nRows;
    private int[] classes;
    private double[][] vectors;
    private double[][] coefficients;
    private double[] intercepts;
    private int[] weights;
    private Kernel kernel;
    private double gamma;
    private double coef0;
    private double degree;

    public SVC (int nClasses, int nRows, double[][] vectors, double[][] coefficients, double[] intercepts, int[] weights, String kernel, double gamma, double coef0, double degree) {
        this.nClasses = nClasses;
        this.classes = new int[nClasses];
        for (int i = 0; i < nClasses; i++) {
            this.classes[i] = i;
        }
        this.nRows = nRows;

        this.vectors = vectors;
        this.coefficients = coefficients;
        this.intercepts = intercepts;
        this.weights = weights;

        this.kernel = Kernel.valueOf(kernel.toUpperCase());
        this.gamma = gamma;
        thi

In [48]:
porter = Porter(svm_model, language='c')
output = porter.export(embed_data=True)
print(output)

#include <stdlib.h>
#include <stdio.h>
#include <math.h>

#define N_FEATURES 22
#define N_CLASSES 2
#define N_VECTORS 169
#define N_ROWS 2
#define N_COEFFICIENTS 1
#define N_INTERCEPTS 1
#define KERNEL_TYPE 'p'
#define KERNEL_GAMMA 0.045454545454545456
#define KERNEL_COEF 0.0
#define KERNEL_DEGREE 3

double vectors[169][22] = {{1.029712237713905, 0.14012794477794924, -0.19824982751343181, -0.8432296400028142, 0.40656202865404567, 0.16289645171177966, 2.278612115023465, -0.6690383093994308, -0.5114723838114789, 0.8735106372181927, 1.7814601887614623, -2.534652044595703, 0.5863846591895536, 0.622441390325499, 0.6319913825853262, 0.0, 0.14203663498716684, -0.2561317410190009, -1.2722157358170676, -0.6701948585135749, -0.5143892000079515, -0.2957296600062443}, {-0.8403433999584713, 0.9532703900465632, -0.19824982751343181, 1.185916567160356, -0.5441892438806311, 0.16289645171177966, -0.4388636369510842, -0.6690383093994308, 0.05347685426934428, -1.1448057498013176, 2.7239310518441737, 0.68

In [39]:
model.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [13]:
model.score(X_test, y_test)

1.0

In [14]:
model.intercept_[0]

0.007726994262295534

In [15]:
model.get_params('true')

{'C': 1.0,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'auto',
 'kernel': 'poly',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [16]:
from sklearn_porter import Porter

In [17]:
porter = Porter(model, language='java')
output = porter.export(embed_data=True)
print(output)

class SVC {

    private enum Kernel { LINEAR, POLY, RBF, SIGMOID }

    private int nClasses;
    private int nRows;
    private int[] classes;
    private double[][] vectors;
    private double[][] coefficients;
    private double[] intercepts;
    private int[] weights;
    private Kernel kernel;
    private double gamma;
    private double coef0;
    private double degree;

    public SVC (int nClasses, int nRows, double[][] vectors, double[][] coefficients, double[] intercepts, int[] weights, String kernel, double gamma, double coef0, double degree) {
        this.nClasses = nClasses;
        this.classes = new int[nClasses];
        for (int i = 0; i < nClasses; i++) {
            this.classes[i] = i;
        }
        this.nRows = nRows;

        this.vectors = vectors;
        this.coefficients = coefficients;
        this.intercepts = intercepts;
        this.weights = weights;

        this.kernel = Kernel.valueOf(kernel.toUpperCase());
        this.gamma = gamma;
        thi

In [18]:
porter = Porter(model, language='c')
output = porter.export(embed_data=True)
print(output)

#include <stdlib.h>
#include <stdio.h>
#include <math.h>

#define N_FEATURES 22
#define N_CLASSES 2
#define N_VECTORS 317
#define N_ROWS 2
#define N_COEFFICIENTS 1
#define N_INTERCEPTS 1
#define KERNEL_TYPE 'p'
#define KERNEL_GAMMA 0.045454545454545456
#define KERNEL_COEF 0.0
#define KERNEL_DEGREE 3

double vectors[317][22] = {{1.029712237713905, 0.9532703900465632, -0.19824982751343181, 1.185916567160356, 0.40656202865404567, 0.16289645171177966, -0.4388636369510842, -0.6690383093994308, 0.05347685426934428, 0.8735106372181927, -0.10348153740396093, 0.6837776537937139, 0.5863846591895536, -1.4810169520224028, 0.6319913825853262, 0.0, 0.14203663498716684, -0.2561317410190009, 0.9480808566164142, -0.250470603921817, 0.2843298100961381, -0.8771690980243297}, {-2.087047158406722, 0.14012794477794924, 1.3730492931881484, 1.185916567160356, -0.5441892438806311, 0.16289645171177966, -0.4388636369510842, -0.6690383093994308, -0.7939470028518905, -1.1448057498013176, 0.8389893256787506, 0.6837

In [19]:
model.dual_coef_ 

array([[-0.6806146 , -0.39297178, -0.00213692, -1.        , -0.057179  ,
        -0.80797589, -0.51776728, -1.        , -0.42415859, -1.        ,
        -1.        , -1.        , -0.27796732, -0.128028  , -1.        ,
        -1.        , -1.        , -0.56573799, -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -0.38490585,
        -1.        , -1.        , -1.        , -1.        , -0.3798593 ,
        -0.00133512, -1.        , -0.15657422, -1.        , -1.        ,
        -1.        , -1.        , -0.14625027, -0.49990971, -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -0.01133171, -0.24765567, -1.        , -1.        ,
        -1.        , -0.17696158, -1.        , -1.        , -0.53191506,
        -1.        , -0.37041803, -0.3917017 , -0.16129033, -0.03580069,
        -1.        , -1.        , -1.        , -0.20483924, -1.        ,
        -1.        , -0.86414596, -0.0454223 , -0.6